add collection name + timestap in publication pipeline statemachine name
MAAP-Project/veda-data-pipelines pull request #18
Opened 2023-04-12 04:32 UTC by emileten

when we run `insert-item` the stateMachine` should now be named like `{collection_name}-{YYYMMDDHHmmSS}`.

2023-04-12 08:10 UTC, sbquinlan requested changes
Thoughts on updating both https://github.com/MAAP-Project/veda-data-pipelines/blob/main/lambdas/proxy/handler.py#L12-L15 and https://github.com/MAAP-Project/veda-data-pipelines/blob/main/lambdas/discovery-trigger/handler.py#L13-L16 as well so that all invocations get named? Otherwise large ingests will just bury the named ones.

2023-04-12 08:10 UTC, sbquinlan commented on scripts/utils.py
> +    timestamp = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
I had some submissions rejected when I did this because the managed to happen the same second. Might just use uuid4 from uuid.

2023-04-12 08:10 UTC, sbquinlan commented on scripts/utils.py
> +    return f"{collection}-{timestamp}"
```suggestion
    return f"{collection[:40]}-{timestamp}"
```

the docs said it has to be less than 80 chars, so you might want to truncate the collection name some of them can be long.

2023-04-12 10:52 UTC, emileten commented
Oh thanks ! Well if it achieves the same purpose and has been used, do you want to submit a PR with it instead of this @sbquinlan

2023-04-20 17:39 UTC, jjfrench commented
Close in favor of #20

2023-04-20 17:39 UTC, closed without merging